/**
 * Thin client for the products API.
 *
 * In this demo, "the API" is the static JSON file at /api/products.json
 * (generated by `npm run gen-api` from src/data/products.ts).
 *
 * In production, point BASE_URL to your real API host.
 */
import { Product } from '../types';

const BASE_URL = '/api';

export interface ProductsResponse {
  meta: {
    total: number;
    generatedAt: string;
    currency: string;
    note?: string;
  };
  data: Product[];
}

/** Fetch the full product catalog. */
export async function fetchProducts(): Promise<ProductsResponse> {
  const res = await fetch(`${BASE_URL}/products.json`, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`Failed to fetch products: ${res.status} ${res.statusText}`);
  return res.json();
}

/** Fetch a single product by slug (client-side filtering for demo). */
export async function fetchProduct(slug: string): Promise<Product | undefined> {
  const all = await fetchProducts();
  return all.data.find(p => p.slug === slug);
}

/** Fetch products filtered by category (cat or subcat). */
export async function fetchProductsByCategory(filter: string): Promise<Product[]> {
  const all = await fetchProducts();
  if (filter === 'all') return all.data;
  return all.data.filter(p => p.cat === filter || p.subcat === filter);
}

/**
 * Demo only — these mutate the LOCAL state via the dispatch you pass in.
 * In a real backend, replace with POST/PUT/DELETE calls + JWT auth.
 */
export const adminApi = {
  /** Create a product. Returns the created entity. */
  async create(product: Product): Promise<Product> {
    // await fetch(`${BASE_URL}/admin/products`, { method:'POST', body: JSON.stringify(product) });
    return product;
  },
  /** Update an existing product. */
  async update(product: Product): Promise<Product> {
    // await fetch(`${BASE_URL}/admin/products/${product.slug}`, { method:'PUT', body: JSON.stringify(product) });
    return product;
  },
  /** Delete a product by slug. */
  async remove(slug: string): Promise<void> {
    // await fetch(`${BASE_URL}/admin/products/${slug}`, { method:'DELETE' });
    void slug;
  },
};
